---
- name: Create New env file for Zookeeper service
  template:
    src: env.zookeeper.j2
    dest: /etc/default/zookeeper
    mode: 0644
    owner: root
    group: root
  notify:
   - Reload SystemD
   - Restart Zookeeper Service

- name: Create Directory for Zookeeper service override
  file:
    path: /etc/systemd/system/zookeeper.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create New file for Zookeeper service override
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/zookeeper.service.d/override.conf
    mode: 0644
    owner: root
    group: root
  notify:
   - Reload SystemD
   - Restart Zookeeper Service

- name: Create New file for Zookeeper service
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
    mode: 0755
    owner: root
    group: root
  notify:
   - Reload SystemD
   - Restart Zookeeper Service

- name: Start and Enable Zookeeper Service
  service:
    name: zookeeper
    state: started
    enabled: yes