---
- name: Create Volume Group
  lvg:
    pvs: "/dev/{{ block_device }}1"
    vg: "{{ lvm_vg_name }}"

- name: Create Logical Volume
  lvol:
    vg: "{{ lvm_vg_name }}"
    lv: "lv-kafka"
    size: 100%FREE
    force: yes

- name: Format Logical Volume
  filesystem:
    dev: "/dev/{{ lvm_vg_name }}/lv-kafka"  
    fstype: xfs
    force: yes