---
# - name: Create Directory Home for Kafka User
#   file:
#     path: "{{ user_home_directory }}"
#     state: directory

- name: Creating System Group Kafka
  group:
    name: kafka
    state: present


- name: Creating User Kafka
  user:
    name: kafka
    groups: kafka
    state: present
    home: "{{ user_home_directory }}"
    shell: "/usr/sbin/nologin"