---
- name: Download Kafka Source Package
  get_url:
    url: http://archive.apache.org/dist/kafka/{{ kafka_version_major }}.{{ kafka_version_minor }}.{{ kafka_version_revision }}/kafka_{{ scala_version_major }}.{{ scala_version_minior}}-{{ kafka_version_major }}.{{ kafka_version_minor }}.{{ kafka_version_revision }}.tgz
    dest: /tmp/kafka.tgz
    mode: 0755

- name: Unarchive Kafka Source
  unarchive:
    src: /tmp/kafka.tgz
    dest: "{{ user_home_directory }}"
    remote_src: yes
    extra_opts: 
    - --strip-components=1

- name: Remove Kafka Source
  file:
    path: /tmp/kafka.tgz
    state: absent

- name: Create Directory for Zookeeper data and logs
  file:
    path: "{{ item }}"
    state: directory
    owner: kafka
    group: kafka
    mode: 0755
  with_items:
    - "{{ user_home_directory }}/data/zookeeper/data"
    - "{{ user_home_directory }}/data/zookeeper/logs"

- name: Create Directory for Kafka data and logs
  file:
    path: "{{ item }}"
    state: directory
    owner: kafka
    group: kafka
    mode: 0755
  with_items:
    - "{{ user_home_directory }}/data/kafka/logs"
    - "{{ user_home_directory }}/data/logs"

- name: Create Symlink Directory for Kafka logs
  file:
    src: "{{ user_home_directory }}/data/logs"
    dest: "{{ user_home_directory }}/logs"
    state: link

- name: Set Permission Chown Kafka Home
  file:
    path: "{{ user_home_directory }}"
    state: directory
    owner: kafka
    group: kafka
    recurse: yes
